apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: corekube-frontend
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: corekube-frontend
  minReplicas: 1
  maxReplicas: 20
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 30
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 0
      policies:
        - periodSeconds: 15
          type: Pods
          value: 20
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
        - periodSeconds: 15
          type: Pods
          value: 20

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: corekube-worker
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: corekube-worker
  minReplicas: 1
  maxReplicas: 20
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 30
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 0
      policies:
        - periodSeconds: 15
          type: Pods
          value: 20
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
        - periodSeconds: 15
          type: Pods
          value: 20

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: corekube-db
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: corekube-db
  minReplicas: 1
  maxReplicas: 20
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 30
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 0
      policies:
        - periodSeconds: 15
          type: Pods
          value: 20
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
        - periodSeconds: 15
          type: Pods
          value: 20
