apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: web
  namespace: nodevoto
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: web
  minReplicas: 1
  maxReplicas: 20
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 30
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 0
    scaleUp:
      stabilizationWindowSeconds: 0

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: voting
  namespace: nodevoto
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: voting
  minReplicas: 1
  maxReplicas: 20
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 30
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 0
    scaleUp:
      stabilizationWindowSeconds: 0

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: gif
  namespace: nodevoto
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: gif
  minReplicas: 1
  maxReplicas: 20
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 30
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 0
    scaleUp:
      stabilizationWindowSeconds: 0
