kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pods-list
rules:
- apiGroups: ["", "apps", "metrics.k8s.io"]
  resources: ["pods", "deployments/scale", "pods/metrics.k8s.io"]
  verbs: ["get", "watch", "list", "patch"]

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pods-list
subjects:
- kind: ServiceAccount
  name: default
  namespace: linkerd-scaler
roleRef:
  kind: ClusterRole
  name: pods-list
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: metrics-pvol
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/metrics"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: metrics-pvol-claim
  namespace: linkerd-scaler
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: linkerd-scaler
  name: watcher
  labels:
    app: watcher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: watcher
  template:
    metadata:
      labels:
        app: watcher
    spec:
      containers:
      - name: watcher
        image: watcher
        imagePullPolicy: Never
        volumeMounts:
            - name: metrics
              mountPath: /metrics
      volumes: 
        - name: metrics
          persistentVolumeClaim:
            claimName: metrics-pvol-claim
