apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2023-11-22T05:55:59Z"
  name: corekube-worker
  namespace: default
  resourceVersion: "757"
  uid: c44a44a2-dfe0-4c26-96f2-bf8212882e4e
spec:
  clusterIP: 10.42.3.10
  clusterIPs:
  - 10.42.3.10
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: worker-s1ap
    port: 5566
    protocol: UDP
    targetPort: 5566
  selector:
    app: corekube-worker
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}