apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2023-11-22T05:56:00Z"
  generation: 1
  name: corekube-db
  namespace: default
  resourceVersion: "1069"
  uid: 1d3da5d9-13ca-4208-a592-1e2714e2bd78
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: corekube-db
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: corekube-db
    spec:
      containers:
      - command:
        - ./corekubeDB
        - $(THIS_POD_IP)
        env:
        - name: THIS_POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        image: andrewferguson/corekube-db:latest
        imagePullPolicy: Always
        name: corekube-db
        ports:
        - containerPort: 7788
          protocol: TCP
        resources:
          limits:
            cpu: 50m
          requests:
            cpu: 50m
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2023-11-22T05:56:47Z"
    lastUpdateTime: "2023-11-22T05:56:47Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2023-11-22T05:56:00Z"
    lastUpdateTime: "2023-11-22T05:56:47Z"
    message: ReplicaSet "corekube-db-85b854b574" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
