apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2023-11-22T05:56:00Z"
  generation: 1
  name: corekube-frontend
  namespace: default
  resourceVersion: "1041"
  uid: 671abf6a-06b8-4c80-be08-228a78978b43
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: corekube-frontend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: corekube-frontend
    spec:
      containers:
      - command:
        - ./corekube_frontend
        - $(THIS_POD_IP)
        - $(COREKUBE_WORKER_SERVICE_HOST)
        - 5G
        env:
        - name: THIS_POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        image: andrewferguson/corekube-frontend:latest
        imagePullPolicy: Always
        name: corekube-frontend
        ports:
        - containerPort: 38412
          protocol: SCTP
        resources:
          limits:
            cpu: 10
          requests:
            cpu: 10
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2023-11-22T05:56:44Z"
    lastUpdateTime: "2023-11-22T05:56:44Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2023-11-22T05:56:00Z"
    lastUpdateTime: "2023-11-22T05:56:44Z"
    message: ReplicaSet "corekube-frontend-6884d7f88f" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1