apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2023-11-22T05:55:59Z"
  generation: 2
  name: corekube-worker
  namespace: default
  resourceVersion: "1135"
  uid: c36c515c-3cd4-4bb6-b22b-1f6d7a41cd55
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: corekube-worker
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: corekube-worker
    spec:
      containers:
      - command:
        - ./corekube_udp_worker
        - $(THIS_POD_IP)
        - $(COREKUBE_DB_SERVICE_HOST)
        - "0"
        env:
        - name: THIS_POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        image: andrewferguson/corekube-worker5g:latest
        imagePullPolicy: Always
        name: corekube-worker
        ports:
        - containerPort: 5566
          name: worker-s1ap
          protocol: UDP
        resources:
          limits:
            cpu: 200m
            memory: 20Gi
          requests:
            cpu: 100m
            memory: 1Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
